// Code generated by github.com/Morkow/gqlgen, DO NOT EDIT.

package model

import (
	external "external"
)

type Address struct {
	ID       external.ObjectID `json:"id"`
	Location *Point            `json:"location"`
}
